name: Docker

on:
  push:
    branches: [master]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: sandermertens/flecs.explorer:latest 
          push: ${{ github.ref == 'refs/heads/master' }}

